Fix: kpartx output is not parsed correctly if run for first time
- Fix shellcheck lints

diff --git a/bin/backup-rpi b/bin/backup-rpi
--- a/bin/backup-rpi
+++ b/bin/backup-rpi
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 #Get location of this script:
 #http://www.ostricher.com/2014/10/the-right-way-to-get-the-directory-of-a-bash-script/
@@ -53,6 +53,10 @@ You must specify a CONFIG_FILE. Others are optional
 EOF
 		exit 0
     ;;
+  *)
+	echo "Invalid option $opt"
+	exit 1
+	;;
   esac
 done
 
@@ -85,10 +89,10 @@ declare -a ext_parts=()
 for part in ${!destpart[@]} #Get partition numbers from config file
 do
 	#Append / if not already to source & dest paths
-	[[ $destpart[$part] == */ ]] || destpart[$part]="${destpart[$part]}/"
-	[[ $destroot[$part] == */ ]] || destroot[$part]="${destroot[$part]}/"
+	[[ ${destpart[$part]} == */ ]] || destpart[part]="${destpart[$part]}/"
+	[[ ${destroot[$part]} == */ ]] || destroot[part]="${destroot[$part]}/"
 	#Get filesystem type for this partition
-	fstype=`/sbin/blkid -s TYPE -o value "/dev/mapper/${device}p${part}"`
+	fstype=$(/sbin/blkid -s TYPE -o value "/dev/mapper/${device}p${part}")
 	echo "${srchost}:${destpart[$part]} -> $destroot${destpart[$part]} (${fstype})"
 	
 	#Set rsync command line to use the default filesystem options
@@ -126,7 +130,7 @@ then
 	do
 		echo "Running zerofree over filesystem ${destpart[$part]} (device file /dev/mapper/${device}p${part})"
 		#@todo iterate over file system
-		zerofree $getopts_zerofree "/dev/mapper/${device}p${part}"
+		zerofree "$getopts_zerofree" "/dev/mapper/${device}p${part}"
 	done
 fi
 
